# SilverStar Sewing Control System Docs

此仓库为中文版的银星缝纫控制系统文档。

https://silverstarscsdocs.readthedocs.io/zh-cn/latest/

## 关于

"SilverStar SCS Docs"(SS-SCS-Docs) 旨在成为有关如何理解和设置银星缝制电控系统功能的权威资源。

## 许可协议

SilverStar SCS Docs is licensed under [Apache License 2.0](LICENSE).

## 贡献

本项目欢迎贡献！请参阅[贡献指南](https://silverstarscsdocs.readthedocs.io/zh-cn/latest/contribute.html)，了解有关我们的写作风格指南以及如何在本地构建本项目以测试您的更改的详细信息。
